import * as Yup from "yup";


export const carrierValidationSchema = Yup.object().shape({
  // Step 1 — Carrier Details
  serviceType: Yup.string().required("Service type is required"),
  carrierName: Yup.string().required("Carrier name is required"),
  contactPerson: Yup.string().nullable(),
  mc: Yup.string().nullable(),
  dot: Yup.string().nullable(),
  fedTaxId: Yup.string().nullable(),
  scacCode: Yup.string().nullable(),
  customCarrierId: Yup.string().nullable(),
  mcpId: Yup.string().nullable(),
  rmisId: Yup.string().nullable(),
  highwayId: Yup.string().nullable(),
  partner: Yup.string().nullable(),
  registration: Yup.string().nullable(),
  dbaName: Yup.string().nullable(),
  status: Yup.boolean(),
  track1099: Yup.boolean(),
  ltlConnectAccountId: Yup.string().nullable(),
  project44AccountNumber: Yup.string().nullable(),
  // Contact
  address: Yup.string().required("Address is required"),
  addressLine2: Yup.string().nullable(),
  city: Yup.string().required("City is required"),
  state: Yup.string().required("State is required"),
  zipCode: Yup.string().required("Zip code is required"),
  phone: Yup.string().required("Phone is required"),
  fax: Yup.string().nullable(),
  email: Yup.string().email("Invalid email").required("Email is required"),
  website: Yup.string().nullable(),
  notes: Yup.string().nullable(),
  // Carrier Configuration
  manageSettlements: Yup.boolean(),
  carrierSettlements: Yup.boolean(),
  manageCompliance: Yup.boolean(),
  manageMaintenance: Yup.boolean(),
  manageInvoicing: Yup.boolean(),
  manageSourcing: Yup.boolean(),
  manageExpense: Yup.boolean(),
  useFactoring: Yup.boolean(),

  // Step 2 — Insurance
  // Primary Liability
  plCompany: Yup.string().nullable(),
  plPhone: Yup.string().nullable(),
  plAgent: Yup.string().nullable(),
  plAgentPhone: Yup.string().nullable(),
  plEmail: Yup.string().nullable(),
  plPolicyNumber: Yup.string().nullable(),
  plExpiration: Yup.string().nullable(),
  plLimit: Yup.string().nullable(),
  plCity: Yup.string().nullable(),
  plState: Yup.string().nullable(),
  plZipCode: Yup.string().nullable(),
  plFax: Yup.string().nullable(),
  plDeductable: Yup.string().nullable(),
  plNotes: Yup.string().nullable(),
  // Cargo Insurance
  ciCompany: Yup.string().nullable(),
  ciPhone: Yup.string().nullable(),
  ciAgent: Yup.string().nullable(),
  ciAgentPhone: Yup.string().nullable(),
  ciEmail: Yup.string().nullable(),
  ciPolicyNbr: Yup.string().nullable(),
  ciExpiration: Yup.string().nullable(),
  ciLimit: Yup.string().nullable(),
  ciCity: Yup.string().nullable(),
  ciState: Yup.string().nullable(),
  ciZipCode: Yup.string().nullable(),
  ciFax: Yup.string().nullable(),
  ciDeductable: Yup.string().nullable(),
  ciNotes: Yup.string().nullable(),
  // General Liability
  glCompany: Yup.string().nullable(),
  glPhone: Yup.string().nullable(),
  glAgent: Yup.string().nullable(),
  glAgentPhone: Yup.string().nullable(),
  glEmail: Yup.string().nullable(),
  glPolicyNumber: Yup.string().nullable(),
  glExpiration: Yup.string().nullable(),
  glLimit: Yup.string().nullable(),
  glCity: Yup.string().nullable(),
  glState: Yup.string().nullable(),
  glZipCode: Yup.string().nullable(),
  glFax: Yup.string().nullable(),
  glDeductable: Yup.string().nullable(),
  glNotes: Yup.string().nullable(),

  // Step 3 — Payable & Remit
  // Factoring Payable To
  fpSameAsCarrier: Yup.boolean(),
  fpName: Yup.string().nullable(),
  fpAddress: Yup.string().nullable(),
  fpCity: Yup.string().nullable(),
  fpState: Yup.string().nullable(),
  fpCountry: Yup.string().nullable(),
  fpZipCode: Yup.string().nullable(),
  fpPhone: Yup.string().nullable(),
  fpFax: Yup.string().nullable(),
  fpEmail: Yup.string().nullable(),
  fpWebsite: Yup.string().nullable(),
  fpContactPerson: Yup.string().nullable(),
  // Invoice Payable To
  ipSameAsCarrier: Yup.boolean(),
  ipName: Yup.string().nullable(),
  ipAddress: Yup.string().nullable(),
  ipCity: Yup.string().nullable(),
  ipState: Yup.string().nullable(),
  ipZipCode: Yup.string().nullable(),
  ipPhone: Yup.string().nullable(),
  ipFax: Yup.string().nullable(),
  ipEmail: Yup.string().nullable(),
  ipWebsite: Yup.string().nullable(),
  ipContactPerson: Yup.string().nullable(),
  // Remit Details
  rdSameAsCarrier: Yup.boolean(),
  remitName: Yup.string().nullable(),
  remitAddress: Yup.string().nullable(),
  remitState2: Yup.string().nullable(),
  remitCity: Yup.string().nullable(),
  remitCountry: Yup.string().nullable(),
  remitZipCode: Yup.string().nullable(),
  remitPhone: Yup.string().nullable(),
  remitFax: Yup.string().nullable(),
  remitEmail: Yup.string().nullable(),
  // Dispatch Details
  dispatchContactName: Yup.string().nullable(),
  dispatchEmail: Yup.string().nullable(),
  dispatchPhone1: Yup.string().nullable(),
  dispatchPhone2: Yup.string().nullable(),
  dispatchPhone3: Yup.string().nullable(),
  // NetSuite Details
  netSuiteSubsidiaryName: Yup.string().nullable(),
  netSuite1099AccountNumber: Yup.string().nullable(),
  purchaseExpenseLineAccount: Yup.string().nullable(),

  // Step 4 — Modes & Certification
  modeLTL: Yup.boolean(),
  modePartial: Yup.boolean(),
  modeTruckLoad: Yup.boolean(),
  modeRail: Yup.boolean(),
  modeIntermodal: Yup.boolean(),
  modeAir: Yup.boolean(),
  modeExpedite: Yup.boolean(),
  modeOcean: Yup.boolean(),
  // Carrier Certification
  hazmatNumber: Yup.string().nullable(),
  ctpatsvINumber: Yup.string().nullable(),
  tankerEndorsedNumOfDrivers: Yup.string().nullable(),
  hazmat: Yup.boolean(),
  smartWay: Yup.boolean(),
  carb: Yup.boolean(),
  twic: Yup.boolean(),
  ctpatCertified: Yup.boolean(),
  tankerEndorsed: Yup.boolean(),
  // Class
  classConestoga: Yup.boolean(),
  classContainers: Yup.boolean(),
  classDecksSpecialized: Yup.boolean(),
  classDecksStandard: Yup.boolean(),
  classDryBulk: Yup.boolean(),
  classFlatBeds: Yup.boolean(),
  classHazardousMaterials: Yup.boolean(),
  classReefers: Yup.boolean(),
  classTankers: Yup.boolean(),
  classVansSpecialized: Yup.boolean(),
  classVansStandard: Yup.boolean(),
  classOther: Yup.boolean(),
  classOtherText: Yup.string().nullable(),

  // Step 5 — Fleet & Banking
  fleetSize: Yup.string().nullable(),
  totalPowerUnits: Yup.string().nullable(),
  numberOfVehicles: Yup.string().nullable(),
  reeferEquipment: Yup.boolean(),
  vanEquipment: Yup.boolean(),
  flatbedStepDeckEquipment: Yup.boolean(),
  // Remit Bank Info
  carrierBankRoutingNumber: Yup.string().nullable(),
  carrierBankAccountNumber: Yup.string().nullable(),
  carrierBankAccountName: Yup.string().nullable(),
  carrierBankName: Yup.string().nullable(),
  carrierBankAddress: Yup.string().nullable(),
  carrierBankPhone: Yup.string().nullable(),
  carrierBankFax: Yup.string().nullable(),
  carrierBankAccountType: Yup.string().nullable(),
  // Agreement
  signatureDate: Yup.string().nullable(),
  signaturePerson: Yup.string().nullable(),
  signaturePersonTitle: Yup.string().nullable(),
  signaturePersonUserName: Yup.string().nullable(),
  signaturePersonPhoneNumber: Yup.string().nullable(),
  isActive: Yup.boolean(),
  // Bill To
  billToEmail: Yup.string().nullable(),
  billToAddress: Yup.string().nullable(),
  billToInstructions: Yup.string().nullable(),
});