import { loadIcons } from "@iconify/react";

// Define all available icons as a const assertion for strict typing
export const AVAILABLE_ICONS = [
  // Heroicons Outline
  "heroicons-outline:arrow-path",
  "heroicons-outline:arrow-right",
  "heroicons-outline:bell",
  "heroicons-outline:building-office",
  "heroicons-outline:calendar",
  "heroicons-outline:chart-bar",
  "heroicons-outline:chevron-up",
  "heroicons-outline:chevron-down",
  "heroicons-outline:chevron-left",
  "heroicons-outline:chevron-right",
  "heroicons-outline:chip",
  "heroicons-outline:clipboard-check",
  "heroicons-outline:clipboard-copy",
  "heroicons-outline:clock",
  "heroicons-outline:cog-6-tooth",
  "heroicons-outline:computer-desktop",
  "heroicons-outline:document",
  "heroicons-outline:document-text",
  "heroicons-outline:dots-horizontal",
  "heroicons-outline:download",
  "heroicons-outline:emoji-happy",
  "heroicons-outline:eye",
  "heroicons-outline:eye-off",
  "heroicons-outline:envelope",
  "heroicons-outline:fire",
  "heroicons-outline:globe-alt",
  "heroicons-outline:home",
  "heroicons-outline:information-circle",
  "heroicons-outline:link",
  "heroicons-outline:location-marker",
  "heroicons-outline:login",
  "heroicons-outline:magnifying-glass",
  "heroicons-outline:mail",
  "heroicons-outline:map",
  "heroicons-outline:map-pin",
  "heroicons-outline:menu-alt-1",
  "heroicons-outline:menu-alt-3",
  "heroicons-outline:moon",
  "heroicons-outline:paper-airplane",
  "heroicons-outline:pencil",
  "heroicons-outline:pencil-alt",
  "heroicons-outline:phone",
  "heroicons-outline:receipt-tax",
  "heroicons-outline:photograph",
  "heroicons-outline:plus",
  "heroicons-outline:refresh",
  "heroicons-outline:search",
  "heroicons-outline:shield-check",
  "heroicons-outline:sun",
  "heroicons-outline:table",
  "heroicons-outline:template",
  "heroicons-outline:translate",
  "heroicons-outline:trash",
  "heroicons-outline:truck",
  "heroicons-outline:user",
  "heroicons-outline:user-circle",
  "heroicons-outline:user-group",
  "heroicons-outline:video-camera",
  "heroicons-outline:view-boards",
  "heroicons-outline:view-grid-add",
  "heroicons-outline:x",
  "heroicons-outline:x-mark",

  // Heroicons (solid)
  "heroicons:arrow-down-tray",
  "heroicons:arrow-left",
  "heroicons:arrow-path",
  "heroicons:arrow-up-tray",
  "heroicons:battery-100",
  "heroicons:bell",
  "heroicons:briefcase",
  "heroicons:building-office",
  "heroicons:building-office-2",
  "heroicons:calendar",
  "heroicons:chart-bar",
  "heroicons:chat-bubble-bottom-center-text",
  "heroicons:check",
  "heroicons:check-circle",
  "heroicons:chevron-double-left",
  "heroicons:chevron-double-right",
  "heroicons:chevron-down",
  "heroicons:chevron-left",
  "heroicons:chevron-right",
  "heroicons:chevron-up",
  "heroicons:chevron-up-down",
  "heroicons:clipboard-document",
  "heroicons:clock",
  "heroicons:cog-6-tooth",
  "heroicons:cpu-chip",
  "heroicons:credit-card",
  "heroicons:currency-dollar",
  "heroicons:device-phone-mobile",
  "heroicons:device-tablet",
  "heroicons:document",
  "heroicons:document-arrow-up",
  "heroicons:document-chart-bar",
  "heroicons:document-text",
  "heroicons:envelope",
  "heroicons:exclamation-triangle",
  "heroicons:eye",
  "heroicons:fire",
  "heroicons:forward",
  "heroicons:globe-alt",
  "heroicons:identification",
  "heroicons:inbox",
  "heroicons:information-circle",
  "heroicons:list-bullet",
  "heroicons:map-pin",
  "heroicons:map-pin-solid",
  "heroicons:pause",
  "heroicons:pencil-square",
  "heroicons:plus",
  "heroicons:plus-circle",
  "heroicons:presentation-chart-line",
  "heroicons:question-mark-circle",
  "heroicons:shield-check",
  "heroicons:shield-exclamation",
  "heroicons:shopping-cart",
  "heroicons:signal-slash",
  "heroicons:squares-plus",
  "heroicons:star",
  "heroicons:trash",
  "heroicons:truck",
  "heroicons:funnel",
  "heroicons:user",
  "heroicons:user-group",
  "heroicons:wrench-screwdriver",
  "heroicons:x-circle",
  "heroicons:x-mark",
  "heroicons:building-storefront",
  "heroicons:arrow-top-right-on-square",
  "heroicons:arrow-up",
  "heroicons:arrow-down",
  "heroicons:arrow-right",
  "heroicons:play",
  "heroicons:backward",
  "heroicons:speaker-wave",
  "heroicons:speaker-x-mark",
  "heroicons:arrows-pointing-in",
  "heroicons:arrows-pointing-out",
  "heroicons:video-camera",
  "heroicons:video-camera-slash",
  "heroicons:bookmark",
  "heroicons:wifi",
  "heroicons:wifi-slash",
  "heroicons:arrow-right-circle",
  "heroicons:exclamation-circle",
  "svg-spinners:ring-resize",

  // Lucide Icons
  "lucide:building-2",
  "lucide:clock",
  "lucide:file-text",
  "lucide:mail",
  "lucide:map-pin",
  "lucide:phone",

  // Material Symbols
  "material-symbols:dashboard-outline-rounded",
  "material-symbols-light:calendar-clock-outline",
  "material-symbols:head-mounted-device-outline-rounded",

  "mdi:math-log",

  "mdi:file-eye-outline",

  // Other Icon Sets
  "akar-icons:arrow-right",
  "bi:check-lg",
  "bi:facebook",
  "bi:instagram",
  "bi:twitter",
  "bx:check-double",
  "bytesize:search",
  "ic:baseline-device-hub",
  "ic:outline-health-and-safety",
  "ion:business-outline",
  "ph:caret-right",
  "ri:customer-service-2-fill",
  "twemoji:delivery-truck",
  "uil:image-v",
  "ix:reboot",
] as const;

// Create a type for available icons
export type AvailableIcon = (typeof AVAILABLE_ICONS)[number];

// Function to preload all icons
export const preloadIcons = (): void => {
  loadIcons([...AVAILABLE_ICONS]);
};

// Helper function to check if an icon is available (for runtime validation)
export const isIconAvailable = (icon: string): icon is AvailableIcon => {
  return (AVAILABLE_ICONS as readonly string[]).includes(icon);
};

// Helper function to get all available icons (for development/debugging)
export const getAllAvailableIcons = (): readonly AvailableIcon[] => {
  return AVAILABLE_ICONS;
};
